version: '3'
services:
  app:
    build: .
    ports:
      - '3030:3000'
    volumes:
      - .:/app
      - go_path:/go
  db:
    image: mysql:8.0.21
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'webuser'
      MYSQL_HOST: 'db'
      MYSQL_PASSWORD: 'webpass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'membership'
volumes:
  go_path: